// <auto-generated />
using System;
using Buchnat.LaptopsApp.DAOSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buchnat.LaptopsApp.DAOSQL.Migrations
{
    [DbContext(typeof(DAOSQL))]
    [Migration("20240124231214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Buchnat.LaptopsApp.DAOSQL.LaptopDBSQL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Processor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProducerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RAM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageInGB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("Buchnat.LaptopsApp.DAOSQL.ProducerDBSQL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });
#pragma warning restore 612, 618
        }
    }
}
